#############################################################################
# Makefile for building: Omega
# Generated by qmake (2.01a) (Qt 4.3.2) on: Fri Sep 24 15:53:06 2010
# Project:  Omega.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.3.2/bin/qmake -unix -o Makefile Omega.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.3.2/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.3.2/include/QtUiTools -I/usr/local/Trolltech/Qt-4.3.2/include/QtCore -I/usr/local/Trolltech/Qt-4.3.2/include/QtCore -I/usr/local/Trolltech/Qt-4.3.2/include/QtGui -I/usr/local/Trolltech/Qt-4.3.2/include/QtGui -I/usr/local/Trolltech/Qt-4.3.2/include/QtXml -I/usr/local/Trolltech/Qt-4.3.2/include/QtXml -I/usr/local/Trolltech/Qt-4.3.2/include/QtSql -I/usr/local/Trolltech/Qt-4.3.2/include/QtSql -I/usr/local/Trolltech/Qt-4.3.2/include -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.3.2/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.3.2/lib -lQtSql -L/usr/local/Trolltech/Qt-4.3.2/lib -pthread -pthread -pthread -pthread -L/usr/X11R6/lib -pthread -pthread -pthread -lQtUiTools -L/root/qt/lib -lQtXml -pthread -pthread -pthread -pthread -lQtGui -pthread -pthread -lSM -lICE -pthread -pthread -lXi -lXrender -lXrandr -lXfixes -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtCore -pthread -lz -lm -pthread -lgthread-2.0 -lglib-2.0 -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.3.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = frmcompras.cpp \
		frmclientes.cpp \
		frmlocalizar.cpp \
		main.cpp \
		omegasis.cpp \
		frmprodutos.cpp \
		frmlocpro.cpp \
		frmvendas.cpp moc_omegasis.cpp \
		moc_subforms.cpp \
		qrc_frmcompras.cpp \
		qrc_frmclientes.cpp \
		qrc_frmlocalizar.cpp \
		qrc_omegasis_res.cpp \
		qrc_frmprodutos.cpp \
		qrc_frmlocpro.cpp \
		qrc_frmvendas.cpp
OBJECTS       = frmcompras.o \
		frmclientes.o \
		frmlocalizar.o \
		main.o \
		omegasis.o \
		frmprodutos.o \
		frmlocpro.o \
		frmvendas.o \
		moc_omegasis.o \
		moc_subforms.o \
		qrc_frmcompras.o \
		qrc_frmclientes.o \
		qrc_frmlocalizar.o \
		qrc_omegasis_res.o \
		qrc_frmprodutos.o \
		qrc_frmlocpro.o \
		qrc_frmvendas.o
DIST          = /usr/local/Trolltech/Qt-4.3.2/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/uitools.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/lex.prf \
		Omega.pro
QMAKE_TARGET  = Omega
DESTDIR       = 
TARGET        = Omega

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_frmclientes.h ui_frmlocalizar.h ui_frmcompras.h ui_frmprodutos.h ui_frmlocpro.h ui_frmvendas.h ui_frmprincipal.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Omega.pro  /usr/local/Trolltech/Qt-4.3.2/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.3.2/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/uitools.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.3.2/lib/libQtSql.prl \
		/usr/local/Trolltech/Qt-4.3.2/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.3.2/lib/libQtXml.prl \
		/usr/local/Trolltech/Qt-4.3.2/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.3.2/lib/libQtUiTools.prl
	$(QMAKE) -unix -o Makefile Omega.pro
/usr/local/Trolltech/Qt-4.3.2/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/uitools.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.3.2/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.3.2/lib/libQtSql.prl:
/usr/local/Trolltech/Qt-4.3.2/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.3.2/lib/libQtXml.prl:
/usr/local/Trolltech/Qt-4.3.2/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.3.2/lib/libQtUiTools.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Omega.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Omega1.0.0 || $(MKDIR) .tmp/Omega1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Omega1.0.0/ && $(COPY_FILE) --parents omegasis.h subforms.h funcoes.h .tmp/Omega1.0.0/ && $(COPY_FILE) --parents frmcompras.qrc frmclientes.qrc frmlocalizar.qrc omegasis_res.qrc frmprodutos.qrc frmlocpro.qrc frmvendas.qrc .tmp/Omega1.0.0/ && $(COPY_FILE) --parents frmcompras.cpp frmclientes.cpp frmlocalizar.cpp main.cpp omegasis.cpp frmprodutos.cpp frmlocpro.cpp frmvendas.cpp .tmp/Omega1.0.0/ && $(COPY_FILE) --parents forms/frmclientes.ui forms/frmlocalizar.ui forms/frmcompras.ui forms/frmprodutos.ui forms/frmlocpro.ui forms/frmvendas.ui forms/frmprincipal.ui .tmp/Omega1.0.0/ && (cd `dirname .tmp/Omega1.0.0` && $(TAR) Omega1.0.0.tar Omega1.0.0 && $(COMPRESS) Omega1.0.0.tar) && $(MOVE) `dirname .tmp/Omega1.0.0`/Omega1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Omega1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_omegasis.cpp moc_subforms.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_omegasis.cpp moc_subforms.cpp
moc_omegasis.cpp: omegasis.h
	/usr/local/Trolltech/Qt-4.3.2/bin/moc $(DEFINES) $(INCPATH) omegasis.h -o moc_omegasis.cpp

moc_subforms.cpp: omegasis.h \
		subforms.h
	/usr/local/Trolltech/Qt-4.3.2/bin/moc $(DEFINES) $(INCPATH) subforms.h -o moc_subforms.cpp

compiler_rcc_make_all: qrc_frmcompras.cpp qrc_frmclientes.cpp qrc_frmlocalizar.cpp qrc_omegasis_res.cpp qrc_frmprodutos.cpp qrc_frmlocpro.cpp qrc_frmvendas.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_frmcompras.cpp qrc_frmclientes.cpp qrc_frmlocalizar.cpp qrc_omegasis_res.cpp qrc_frmprodutos.cpp qrc_frmlocpro.cpp qrc_frmvendas.cpp
qrc_frmcompras.cpp: frmcompras.qrc \
		forms/frmcompras.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/rcc -name frmcompras frmcompras.qrc -o qrc_frmcompras.cpp

qrc_frmclientes.cpp: frmclientes.qrc \
		forms/frmclientes.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/rcc -name frmclientes frmclientes.qrc -o qrc_frmclientes.cpp

qrc_frmlocalizar.cpp: frmlocalizar.qrc \
		forms/frmlocalizar.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/rcc -name frmlocalizar frmlocalizar.qrc -o qrc_frmlocalizar.cpp

qrc_omegasis_res.cpp: omegasis_res.qrc \
		forms/frmprincipal.ui \
		forms/input.txt
	/usr/local/Trolltech/Qt-4.3.2/bin/rcc -name omegasis_res omegasis_res.qrc -o qrc_omegasis_res.cpp

qrc_frmprodutos.cpp: frmprodutos.qrc \
		forms/frmprodutos.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/rcc -name frmprodutos frmprodutos.qrc -o qrc_frmprodutos.cpp

qrc_frmlocpro.cpp: frmlocpro.qrc \
		forms/frmlocpro.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/rcc -name frmlocpro frmlocpro.qrc -o qrc_frmlocpro.cpp

qrc_frmvendas.cpp: frmvendas.qrc \
		forms/frmvendas.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/rcc -name frmvendas frmvendas.qrc -o qrc_frmvendas.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_frmclientes.h ui_frmlocalizar.h ui_frmcompras.h ui_frmprodutos.h ui_frmlocpro.h ui_frmvendas.h ui_frmprincipal.h
compiler_uic_clean:
	-$(DEL_FILE) ui_frmclientes.h ui_frmlocalizar.h ui_frmcompras.h ui_frmprodutos.h ui_frmlocpro.h ui_frmvendas.h ui_frmprincipal.h
ui_frmclientes.h: forms/frmclientes.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/uic forms/frmclientes.ui -o ui_frmclientes.h

ui_frmlocalizar.h: forms/frmlocalizar.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/uic forms/frmlocalizar.ui -o ui_frmlocalizar.h

ui_frmcompras.h: forms/frmcompras.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/uic forms/frmcompras.ui -o ui_frmcompras.h

ui_frmprodutos.h: forms/frmprodutos.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/uic forms/frmprodutos.ui -o ui_frmprodutos.h

ui_frmlocpro.h: forms/frmlocpro.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/uic forms/frmlocpro.ui -o ui_frmlocpro.h

ui_frmvendas.h: forms/frmvendas.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/uic forms/frmvendas.ui -o ui_frmvendas.h

ui_frmprincipal.h: forms/frmprincipal.ui
	/usr/local/Trolltech/Qt-4.3.2/bin/uic forms/frmprincipal.ui -o ui_frmprincipal.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

frmcompras.o: frmcompras.cpp subforms.h \
		omegasis.h \
		funcoes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmcompras.o frmcompras.cpp

frmclientes.o: frmclientes.cpp subforms.h \
		omegasis.h \
		funcoes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmclientes.o frmclientes.cpp

frmlocalizar.o: frmlocalizar.cpp subforms.h \
		omegasis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmlocalizar.o frmlocalizar.cpp

main.o: main.cpp omegasis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

omegasis.o: omegasis.cpp omegasis.h \
		subforms.h \
		database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o omegasis.o omegasis.cpp

frmprodutos.o: frmprodutos.cpp subforms.h \
		omegasis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmprodutos.o frmprodutos.cpp

frmlocpro.o: frmlocpro.cpp subforms.h \
		omegasis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmlocpro.o frmlocpro.cpp

frmvendas.o: frmvendas.cpp subforms.h \
		omegasis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmvendas.o frmvendas.cpp

moc_omegasis.o: moc_omegasis.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_omegasis.o moc_omegasis.cpp

moc_subforms.o: moc_subforms.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_subforms.o moc_subforms.cpp

qrc_frmcompras.o: qrc_frmcompras.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_frmcompras.o qrc_frmcompras.cpp

qrc_frmclientes.o: qrc_frmclientes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_frmclientes.o qrc_frmclientes.cpp

qrc_frmlocalizar.o: qrc_frmlocalizar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_frmlocalizar.o qrc_frmlocalizar.cpp

qrc_omegasis_res.o: qrc_omegasis_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_omegasis_res.o qrc_omegasis_res.cpp

qrc_frmprodutos.o: qrc_frmprodutos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_frmprodutos.o qrc_frmprodutos.cpp

qrc_frmlocpro.o: qrc_frmlocpro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_frmlocpro.o qrc_frmlocpro.cpp

qrc_frmvendas.o: qrc_frmvendas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_frmvendas.o qrc_frmvendas.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

